import './globals.css'
import { Inter } from 'next/font/google'
import Header from '../components/header'
import { NextUIProvider } from '@nextui-org/react'; 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Epická stránka',
  description: 'Generated by create next app',
  icon: '../../public/img/icon.png'
}

export default function RootLayout({
  children, 
}: {
  children: React.ReactNode
}) {

  return (   
    <>
      <html lang='en'>
        <head>
          <link rel="shortcut icon" href={metadata.icon} />
        </head>
        <body className={inter.className}>
          <Header/>
            {children} 
        </body>
      </html>
    </> 
  )
}
